cors_origin:
  - "*"        # 允许跨域访问列表，如果要允许所有域名访问，设置为*即可，此设置只应用于独立http请求

app:
  app_name: "ChainClientManageSystem" # 应用名称
  version: "v1.0.0"       # 版本
  port: 8080              # 服务启用端口
  run_mode: release       # 可选dev、release模式

db:
  host: "192.168.1.104"   # host
  port: 8086              # port
  user: "root"            # user
  password: "root"        # password
  salt: "salt"            # salt
  aes_key: "this_is_a_aes_key_length_32_____"      # aes_key
  aes_iv: "0123456789012345"            # aes_iv
  dbname: "ca_mysql"      # dbname
  max_idle_conn: 5        # 最大空闲连接数
  max_open_conn: 20       # 最大连接数
  max_idle_time: 300      # 最大空闲时间

redis:
  rhost: "192.168.1.104"
  rport: 8089
  rdb: 0
  passwd: ''
  poolsize: 100

cache:
  session_expired: 7200   # second
  user_expired: 300       # second
  chain_client_expired: 7200 # second

log:
  log_pattern: file            # 可选stdout, stderr, file模式
  log_path: ./log/server.log   # 日志路径
  save_days: 5                 # 保存天数
  level: trace                 # panic,fatal,error,warn,info,debug,trace

chain:
  chainid: "test1"

chainca:
  url: "http://192.168.1.104:8096"

chainnode:
  chain_node_url: "192.168.1.104:12301"